id: P046BC64C
initial_creation_type: input
source_metadata:
  Title: Abhidharmakoṣabhāṣyam
  Editor: Pradhan, Prahlad
  Publisher: K.P.Jayaswal Research Institute
  Place of Publication: Patna, India
  Year: '1975'
  Prathamaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturthaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcamaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaṣṭhaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptamaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭamaṃ kośasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:17:02.797071'
last_modified_at: '2022-03-08T16:17:02.797079'
